/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc_gui_4ax;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class Main_Window extends javax.swing.JFrame {
        
    
        Connection con=null;
        PreparedStatement stmt_selectALL=null;
        PreparedStatement stmt_selectALL2=null;
        PreparedStatement stmt_add=null;
        PreparedStatement stmt_add2=null;
        PreparedStatement stmt_del=null;
        PreparedStatement stmt_del2=null;
        ResultSet res_selectAll=null; 
        ResultSet res_selectAll2=null;
   
    /**
     * Creates new form Main_Window
     */
        
    public Main_Window() {
        initComponents();
        
        try { 
           Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException ex){
           System.out.println("Datenbank kann nicht geladen werden.");
           
        javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht geladen werden.");
        System.exit(1);
       }
        
        //Select 
       
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Server = new javax.swing.JLabel();
        Port = new javax.swing.JLabel();
        Connect = new javax.swing.JButton();
        Disconnect = new javax.swing.JButton();
        Server_INPUT = new javax.swing.JTextField();
        Port_INPUT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtEName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtComm = new javax.swing.JTextField();
        txtJob = new javax.swing.JTextField();
        btnAddEmployee = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        nachVorne = new javax.swing.JButton();
        Zurück = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMgr = new javax.swing.JTextField();
        txtDeptno = new javax.swing.JTextField();
        txtHiredate = new javax.swing.JTextField();
        User = new javax.swing.JLabel();
        Database = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDeptno2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDName = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAddDepartment = new javax.swing.JButton();
        btnDeleteDept = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Server.setText("Server");

        Port.setText("Port");

        Connect.setText("Connect");
        Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectActionPerformed(evt);
            }
        });

        Disconnect.setText("Disconnect");
        Disconnect.setEnabled(false);
        Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectActionPerformed(evt);
            }
        });

        Server_INPUT.setText("localhost");
        Server_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Server_INPUTActionPerformed(evt);
            }
        });

        Port_INPUT.setText("3306");

        jLabel1.setText("ID");

        jLabel2.setText("EName");

        jLabel3.setText("Salary");

        jLabel4.setText("Comm");

        jLabel5.setText("Job");

        txtID.setEditable(false);
        txtID.setText("      ");
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtEName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtENameActionPerformed(evt);
            }
        });

        txtJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobActionPerformed(evt);
            }
        });

        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Employee");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        nachVorne.setText(">");
        nachVorne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nachVorneActionPerformed(evt);
            }
        });

        Zurück.setText("<");
        Zurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZurückActionPerformed(evt);
            }
        });

        jLabel6.setText("Custom SQL Statement for SELECT");

        jTextField1.setEditable(false);
        jTextField1.setText("root");

        jTextField2.setEditable(false);

        jTextField3.setText("scott");

        jLabel7.setText("Mgr");

        jLabel8.setText("Deptno");

        jLabel9.setText("Hiredate");

        User.setText("User");

        Database.setText("Database");

        Password.setText("Password");

        jLabel10.setText("Deptno");

        jLabel11.setText("DName");

        jLabel12.setText("Loc");

        txtLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocActionPerformed(evt);
            }
        });

        jLabel13.setText("Tabelle Emp");

        jLabel14.setText("Tabelle Dept");

        btnAddDepartment.setText("Add Department");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        btnDeleteDept.setText("Delete Department");
        btnDeleteDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDeptActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtJob, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtComm, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSalary, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(txtMgr))
                                    .addComponent(txtDeptno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHiredate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Zurück)
                                        .addGap(18, 18, 18)
                                        .addComponent(nachVorne)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Server)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Server_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Port)
                                        .addGap(18, 18, 18)
                                        .addComponent(Port_INPUT)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Password, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddDepartment))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(62, 62, 62)
                                        .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(43, 43, 43))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                                        .addComponent(jTextField2))
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtDeptno2)
                                                    .addComponent(txtDName))
                                                .addGap(154, 154, 154))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Database)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(Disconnect)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addGap(170, 170, 170))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnDeleteDept))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnClear)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Disconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Server)
                            .addComponent(Server_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Connect)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(User)
                            .addComponent(Database))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Port)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Port_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Zurück)
                                    .addComponent(nachVorne))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDeptno2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddEmployee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDeptno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHiredate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnAddDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteDept)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    private void ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectActionPerformed
        try{
         con = DriverManager.getConnection("jdbc:mysql://" + Server_INPUT.getText() + ":3306/1819_4ax_antoniojakova_scott","root", "");
         Connect.setEnabled(false);
         Disconnect.setEnabled(true);
         Server_INPUT.setEnabled(false);
        }
        
        catch(SQLException ex){
            System.out.println("Verbindung mit der Datenbank konnte nicht hergestellt werden.");
            javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht geladen werden.");
            
        }
         try {
        stmt_selectALL = con.prepareStatement("SELECT * FROM EMP");
        res_selectAll= stmt_selectALL.executeQuery();
        
        stmt_selectALL2 = con.prepareStatement("SELECT * FROM DEPT");
        res_selectAll2= stmt_selectALL2.executeQuery();
        
        
        if(res_selectAll.next()){
        int empno= res_selectAll.getInt("Empno");
        String Ename = res_selectAll.getString("Ename");
        int salary = res_selectAll.getInt("Sal");
        String job = res_selectAll.getString("Job");
        double comm = res_selectAll.getInt("Comm");
        int mgr=res_selectAll.getInt("Mgr");
        String hiredate=res_selectAll.getString("Hiredate");
        int deptno=res_selectAll.getInt("Deptno");
        
        
        txtID.setText(""+empno);
        txtEName.setText(Ename);
        txtSalary.setText(""+salary); 
        txtJob.setText(job);
        txtComm.setText(""+comm);
        txtMgr.setText(""+mgr);
        txtHiredate.setText(hiredate);
        txtDeptno.setText(""+deptno);
        
        }
        
        if(res_selectAll2.next()){
        
        int deptno2=res_selectAll2.getInt("Deptno");
        String Dname = res_selectAll2.getString("Dname");
        String loc = res_selectAll2.getString("Loc");
        
        
        txtDeptno.setText(""+deptno2);
        txtDName.setText(Dname);
        txtLoc.setText(loc);
        
          
        }
            stmt_add =con.prepareStatement(
                "INSERT INTO EMP (Ename,job,mgr,hiredate,sal,comm,deptno) values(?,?,?,?,?,?,?)"
            ); 
            
            stmt_add2 =con.prepareStatement(
                "INSERT INTO DEPT (deptno,Dname,loc) values(?,?,?)"
            ); 
        }catch(SQLException ex){
            ex.printStackTrace();
             System.out.println("konnte nicht gemacht werden.");
             javax.swing.JOptionPane.showMessageDialog(this, "Selekt kann nicht gemacht werden.");
        }
        
    }//GEN-LAST:event_ConnectActionPerformed

    private void Server_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Server_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Server_INPUTActionPerformed

    private void DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectActionPerformed
         try{
        con.close();
      
         Connect.setEnabled(true);
         Disconnect.setEnabled(true);
         Server_INPUT.setEnabled(false);
        }
        
        catch(SQLException ex){
            System.out.println("Verbindung mit der Datenbank konnte nicht hergestellt werden.");
            javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht geladen werden.");
            
        }
    }//GEN-LAST:event_DisconnectActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtENameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtENameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtENameActionPerformed

    private void txtJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobActionPerformed

    private void nachVorneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nachVorneActionPerformed
         try {
        if(res_selectAll.next()){
        int empno= res_selectAll.getInt("Empno");
        String Ename = res_selectAll.getString("Ename");
        int salary = res_selectAll.getInt("Sal");
        String job = res_selectAll.getString("Job");
        double comm = res_selectAll.getInt("Comm");
        int mgr=res_selectAll.getInt("Mgr");
        String hiredate=res_selectAll.getString("Hiredate");
        int deptno=res_selectAll.getInt("Deptno");
        
        txtID.setText(""+empno);
        txtEName.setText(Ename);
        txtSalary.setText(""+salary);
        txtJob.setText(job);
        txtComm.setText(""+comm);
        txtMgr.setText(""+mgr);
        txtHiredate.setText(hiredate);
        txtDeptno.setText(""+deptno);
       
        }else{
            res_selectAll.beforeFirst();
        }
        
          if(res_selectAll2.next()){
        int deptno2=res_selectAll2.getInt("Deptno");
        String Dname = res_selectAll2.getString("Dname");
        String loc = res_selectAll2.getString("Loc");
        
        txtDeptno2.setText(""+deptno2);
        txtDName.setText(Dname);
        txtLoc.setText(loc);
        }
        else{
            res_selectAll2.beforeFirst();
              }
        
        }catch(SQLException ex){
            
             System.out.println("konnte nicht gemacht werden.");
             javax.swing.JOptionPane.showMessageDialog(this, "Select kann nicht gemacht werden.");
        }
    }//GEN-LAST:event_nachVorneActionPerformed

    private void ZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZurückActionPerformed
 try {
           if(res_selectAll.previous()){
       int empno= res_selectAll.getInt("Empno");
        String Ename = res_selectAll.getString("Ename");
        int salary = res_selectAll.getInt("Sal");
        String job = res_selectAll.getString("Job");
        double comm = res_selectAll.getInt("Comm");
        int mgr=res_selectAll.getInt("Mgr");
        String hiredate=res_selectAll.getString("Hiredate");
        int deptno=res_selectAll.getInt("Deptno");
        
        
        txtID.setText(""+empno);
        txtEName.setText(Ename);
        txtSalary.setText(""+salary);
        txtJob.setText(job);
        txtComm.setText(""+comm);
        txtMgr.setText(""+mgr);
        txtHiredate.setText(hiredate);
        txtDeptno.setText(""+deptno);
       }
        else{
            res_selectAll.afterLast();
          }
           
        if(res_selectAll2.previous()){
        int deptno2=res_selectAll2.getInt("Deptno");
        String Dname = res_selectAll2.getString("Dname");
        String loc = res_selectAll2.getString("Loc");
        
        txtDeptno2.setText(""+deptno2);
        txtDName.setText(Dname);
        txtLoc.setText(loc);
        }
        else{
            res_selectAll2.afterLast();
              }
        
        
        }catch(SQLException ex){
             System.out.println("konnte nicht gemacht werden.");
             javax.swing.JOptionPane.showMessageDialog(this, "Select kann nicht gemacht werden.");
        }        
    }//GEN-LAST:event_ZurückActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
  try{
        	stmt_del = con.prepareStatement(
					"DELETE FROM EMP WHERE EMPNO = ?");
               
                
	        int id = Integer.parseInt(txtID.getText());
	        stmt_del.setInt(1, id);
	        int rows_deleted = stmt_del.executeUpdate();

	        
	        if(rows_deleted > 0){
	        javax.swing.JOptionPane.showMessageDialog(this, "Employer deleted successfully");

	        }
	        else{
	            javax.swing.JOptionPane.showMessageDialog(this, "Error!");
	        }
	        

		} catch (SQLException e) {
			e.printStackTrace();
		} 
    	txtID.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
       
       try{
         stmt_add.setString(1, txtEName.getText());

       stmt_add.setString(2, txtJob.getText());

       int mgr=Integer.parseInt(txtMgr.getText());
       stmt_add.setInt(3, mgr);

       Date hireDate = null;
      	try {
		hireDate = new SimpleDateFormat("yyyy-MM-dd").parse(txtHiredate.getText());
      	} catch (ParseException e) {
		e.printStackTrace();
      	}
        
       java.sql.Date date = new java.sql.Date(hireDate.getTime());
       stmt_add.setDate(4, date);

       double sal = Double.parseDouble(txtSalary.getText());
       stmt_add.setDouble(5, sal);
       
       
       double comm = Double.parseDouble(txtComm.getText());
       stmt_add.setDouble(6, comm);
       
       int deptno=Integer.parseInt(txtDeptno.getText());
       stmt_add.setInt(7, deptno);
       
       
       int rows_changed=stmt_add.executeUpdate();
       
       if(rows_changed > 0){
       javax.swing.JOptionPane.showMessageDialog(this, "Angestellter wurde eingefügt");

       }
       else{
           javax.swing.JOptionPane.showMessageDialog(this, "Angestellter wurde nicht eingefügt");
       }
       }
       
       catch(SQLException ex){
           ex.printStackTrace();
             System.out.println("Error adding employeee");
             javax.swing.JOptionPane.showMessageDialog(this, "Select kann nicht gemacht werden.");
       }
       
       
       
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void txtLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocActionPerformed

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
try{
        
       int deptno2=Integer.parseInt(txtDeptno2.getText());
       stmt_add2.setInt(1, deptno2);
       
       stmt_add2.setString(2, txtDName.getText());
       stmt_add2.setString(3, txtLoc.getText());


       int rows_changed=stmt_add2.executeUpdate();
       
       if(rows_changed > 0){
       javax.swing.JOptionPane.showMessageDialog(this, "Department wurde eingefügt");

       }
       else{
           javax.swing.JOptionPane.showMessageDialog(this, "Department wurde nicht eingefügt");
       }
       }
       
       catch(SQLException ex){
           ex.printStackTrace();
             System.out.println("Error adding department");
             javax.swing.JOptionPane.showMessageDialog(this, "Select kann nicht gemacht werden.");
       }
       
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnDeleteDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeptActionPerformed
try{
        	stmt_del2 = con.prepareStatement(
					"DELETE FROM EMP WHERE DEPT = ?");
               
                
	        int id = Integer.parseInt(txtID.getText());
	        stmt_del2.setInt(1, id);
	        int rows_deleted = stmt_del2.executeUpdate();

	        
	        if(rows_deleted > 0){
	        javax.swing.JOptionPane.showMessageDialog(this, "Dept deleted successfully");

	        }
	        else{
	            javax.swing.JOptionPane.showMessageDialog(this, "Error!");
	        }
	        

		} catch (SQLException e) {
			e.printStackTrace();
		} 
    	txtID.setText("");
    }//GEN-LAST:event_btnDeleteDeptActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtEName.setText("");
        txtSalary.setText("");
        txtJob.setText("");
        txtComm.setText("");
        txtMgr.setText("");
        txtHiredate.setText("");
        txtDeptno.setText("");
        
        txtDeptno2.setText("");
        
        
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connect;
    private javax.swing.JLabel Database;
    private javax.swing.JButton Disconnect;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Port;
    private javax.swing.JTextField Port_INPUT;
    private javax.swing.JLabel Server;
    private javax.swing.JTextField Server_INPUT;
    private javax.swing.JLabel User;
    private javax.swing.JButton Zurück;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteDept;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton nachVorne;
    private javax.swing.JTextField txtComm;
    private javax.swing.JTextField txtDName;
    private javax.swing.JTextField txtDeptno;
    private javax.swing.JTextField txtDeptno2;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtHiredate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtMgr;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
